"""Built-in command manifests for the Apollo router (md §4.5).

These manifests are deterministic: v0.4 P0 does not call an external
LLM to route commands. Each :class:`CommandIntent` describes a known,
safe-by-default internal command plus its risk / network / budget /
side-effect / approval profile.

The manifest list intentionally covers the surface required by md §4.5:
readiness checks, tests, lint, typecheck, mock model call, policy
explain, workbench dry-run, fusion / mad-dog planning, status, history,
approval listing, and the doctor environment check. A representative
high-risk release-mutation command (``git.tag_release``) is included to
prove natural-language side effects are blocked behind approval.
"""

from __future__ import annotations

from loopos.intent.schema import CommandIntent

BUILTIN_COMMANDS: tuple[CommandIntent, ...] = (
    CommandIntent(
        command_id="readiness.release_check",
        display_name="Release readiness check",
        description="Run the standard validation gates used before a LoopOS release.",
        aliases=(
            "release",
            "ready",
            "can i release",
            "发布",
            "能不能发布",
            "能否发布",
            "可以发布吗",
            "readiness",
            "发布检查",
        ),
        task_types=("release_readiness",),
        argv_template=("python", "scripts/v0_3_readiness_check.py", "--json"),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("检查这个仓库能不能发布", "can I release this repo"),
    ),
    CommandIntent(
        command_id="test.fast",
        display_name="Fast test suite",
        description="Run the fast (not slow) pytest suite.",
        aliases=("test", "tests", "pytest", "跑测试", "单元测试", "run tests"),
        task_types=("test",),
        argv_template=("python", "-m", "pytest", "-m", "not slow", "-q"),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("跑一次快速测试", "run the fast tests"),
    ),
    CommandIntent(
        command_id="test.slow",
        display_name="Slow test suite",
        description="Run the slow pytest suite.",
        aliases=("slow test", "slow tests", "完整测试", "慢测试"),
        task_types=("test",),
        argv_template=("python", "-m", "pytest", "-m", "slow", "-q"),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("run the slow tests", "跑完整测试"),
    ),
    CommandIntent(
        command_id="lint.ruff",
        display_name="Ruff lint check",
        description="Run the ruff linter across the repository.",
        aliases=("lint", "ruff", "代码检查", "lint check"),
        task_types=("lint",),
        argv_template=("python", "-m", "ruff", "check", "."),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("run ruff", "做一次 lint 检查"),
    ),
    CommandIntent(
        command_id="typecheck.mypy",
        display_name="Mypy type check",
        description="Run mypy static type checking on the loopos package and tests.",
        aliases=("typecheck", "mypy", "type check", "类型检查"),
        task_types=("typecheck",),
        argv_template=("python", "-m", "mypy", "loopos", "tests"),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("run mypy", "做类型检查"),
    ),
    CommandIntent(
        command_id="readiness.v0_2",
        display_name="v0.2 readiness check",
        description="Run the v0.2 readiness proof (regression guard).",
        aliases=("v0.2 readiness", "v0_2 readiness", "0.2 readiness"),
        task_types=("release_readiness",),
        argv_template=("python", "scripts/v0_2_readiness_check.py", "--json"),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("run v0.2 readiness",),
    ),
    CommandIntent(
        command_id="readiness.v0_3",
        display_name="v0.3 readiness check",
        description="Run the v0.3 readiness proof.",
        aliases=("v0.3 readiness", "v0_3 readiness", "0.3 readiness"),
        task_types=("release_readiness",),
        argv_template=("python", "scripts/v0_3_readiness_check.py", "--json"),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("run v0.3 readiness",),
    ),
    CommandIntent(
        command_id="anti_bloat.check",
        display_name="Anti-bloat check",
        description="Run the anti-bloat structural check.",
        aliases=("anti-bloat", "anti bloat", "bloat", "膨胀检查"),
        task_types=("release_readiness",),
        argv_template=("python", "scripts/anti_bloat_check.py", "--json"),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("run anti-bloat check",),
    ),
    CommandIntent(
        command_id="model.mock_call",
        display_name="Mock model call",
        description="Run a model call through the deterministic mock provider (no network, no spend).",
        aliases=(
            "mock model call",
            "mock call",
            "mock provider",
            "用 mock provider 跑一次模型调用",
            "模型调用",
            "model call",
        ),
        task_types=("model_call",),
        argv_template=(
            "python",
            "-m",
            "loopos.cli.app",
            "providers-runtime",
            "call",
            "mock",
            "--model",
            "mock-model",
            "--dry-run",
            "--json",
        ),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("用 mock provider 跑一次模型调用", "run a mock model call"),
    ),
    CommandIntent(
        command_id="policy.explain_dangerous",
        display_name="Explain a dangerous command",
        description="Ask Policy OS why a shell command is dangerous (read-only explanation).",
        aliases=(
            "explain curl | bash",
            "explain dangerous",
            "why is this dangerous",
            "为什么危险",
            "policy explain",
            "解释危险命令",
        ),
        task_types=("policy_explain",),
        argv_template=(
            "python",
            "-m",
            "loopos.cli.app",
            "policy",
            "explain",
            "--cmd",
            "<command>",
        ),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("explain why curl | bash is dangerous", "解释 curl | bash 为什么危险"),
    ),
    CommandIntent(
        command_id="workbench.dry_run",
        display_name="Workbench dry-run",
        description="Run the governed Workbench in dry-run mode (no side effects).",
        aliases=("workbench", "工作台", "workbench dry-run"),
        task_types=("workbench",),
        argv_template=(
            "python",
            "-m",
            "loopos.cli.app",
            "workbench",
            "--dry-run",
            "--json",
        ),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("dry-run the workbench",),
    ),
    CommandIntent(
        command_id="fusion.plan",
        display_name="Fusion planning",
        description="Plan a multi-model fusion route (planning-only, no execution, no authority delta).",
        aliases=("fusion", "fusion plan", "fusion route", "融合规划"),
        task_types=("fusion_planning",),
        argv_template=(
            "python",
            "-m",
            "loopos.cli.app",
            "fusion-router",
            "--action",
            "plan",
            "--json",
        ),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        planning_only=True,
        example_goals=("plan a fusion route",),
    ),
    CommandIntent(
        command_id="mad_dog.plan",
        display_name="Mad Dog planning",
        description=(
            "Plan a high-density multi-model escalation (planning-only). "
            "Mad Dog increases intelligence density, not authority."
        ),
        aliases=(
            "mad dog",
            "mad-dog",
            "maddog",
            "疯狗模式",
            "疯狗",
            "开启疯狗模式",
        ),
        task_types=("mad_dog_planning",),
        argv_template=(
            "python",
            "-m",
            "loopos.cli.app",
            "mad-dog",
            "--action",
            "plan",
            "--json",
        ),
        risk_level="low",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        planning_only=True,
        example_goals=("这个 bug 修了三次还失败，开启疯狗模式分析",),
    ),
    CommandIntent(
        command_id="status.summary",
        display_name="Runtime status summary",
        description="Show a lightweight runtime status summary.",
        aliases=("status", "状态", "runtime status"),
        task_types=("status",),
        argv_template=("python", "-m", "loopos.cli.app", "status"),
        risk_level="none",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("show status",),
    ),
    CommandIntent(
        command_id="doctor.environment",
        display_name="Doctor environment check",
        description="Diagnose the local LoopOS setup (Python, git, optional deps, readiness scripts).",
        aliases=("doctor", "诊断", "环境检查", "diagnose"),
        task_types=("doctor",),
        argv_template=("python", "-m", "loopos.cli.app", "doctor"),
        risk_level="none",
        network=False,
        spends_budget=False,
        side_effects=False,
        requires_approval=False,
        safe_by_default=True,
        example_goals=("diagnose my setup",),
    ),
    CommandIntent(
        command_id="git.tag_release",
        display_name="Create release tag",
        description="Create a public release tag. This is a release mutation and requires approval.",
        aliases=("tag", "打 tag", "create release tag", "publish version", "打标签", "发布版本"),
        task_types=("release_readiness",),
        argv_template=("git", "tag", "-a", "<version>", "<head>", "-m", "<message>"),
        risk_level="high",
        network=False,
        spends_budget=False,
        side_effects=True,
        requires_approval=True,
        safe_by_default=False,
        example_goals=("打 v0.4.0 tag", "tag v0.4.0 and push"),
    ),
)


__all__ = ["BUILTIN_COMMANDS"]
